name: CI

on: [push]

jobs:
  test_js:
    name: Test Javascript
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Authenticate GitHub Package Registry
      run: echo -e "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}\nregistry=https://npm.pkg.github.com/ColbyCommunications" > ~/.npmrc
    - name: Install NPM Dependencies
      run: npm install
      env:
        NODE_AUTH_TOKEN: ${{ secrets.WEBMASTER_SECRET }}
    - name: Run Jest
      run: npm run testjs