name: CI

on: [push]

jobs:
  test_js:
    name: Test Javascript
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
          node-version: 10
          registry-url: 'https://npm.pkg.github.com/ColbyCommunications'
      env:
        NODE_AUTH_TOKEN: ${{ secrets.WEBMASTER_SECRET }}
    - name: Install NPM Dependencies
      run: npm install
      env:
        NODE_AUTH_TOKEN: ${{ secrets.WEBMASTER_SECRET }}
    - name: Run Jest
      run: npm run testjs