name: CI

on: [push]

jobs:
  test_js:
    name: Test Javascript
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install NPM Dependencies
      run: npm install
    - name: Run Jest
      run: npm run testjs