name: CI

on: [push]

jobs:
  test_js:
    name: Test Javascript
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Authenticate GitHub Package Registry
      run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.WEBMASTER_SECRET }}" > ~/.npmrc
    - name: Install NPM Dependencies
      run: npm install
      env:
        NODE_AUTH_TOKEN: '${{ secrets.WEBMASTER_SECRET }}'
    - name: Run Jest
      run: npm run testjs
  test_php:
    name: Test PHP
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install Composer Dependencies
      run: composer install
    - name: PHPUnit
      run: npm run testphp