name: CI

on: [push]

jobs:
  test_js:
    name: Test Javascript
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Authenticate GitHub Package Registry
      run: echo "//npm.pkg.github.com/:_authToken=e95d8b5943038cb9f64d0ed4c150835a2a853c0b" > ~/.npmrc
    - name: Install NPM Dependencies
      run: npm install
      env:
        NODE_AUTH_TOKEN: 'e95d8b5943038cb9f64d0ed4c150835a2a853c0b'
    - name: Run Jest
      run: npm run testjs