name: CI

on: [push]

jobs:
  test_js:
    name: Test Javascript
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Authenticate GitHub Package Registry
      run: echo "//npm.pkg.github.com/:_authToken=98c3fe70784634ec4df2e92665d035f7d89b35b7" > ~/.npmrc
    - name: Install NPM Dependencies
      run: npm install
      env:
        NODE_AUTH_TOKEN: '98c3fe70784634ec4df2e92665d035f7d89b35b7'
    - name: Run Jest
      run: npm run testjs